### ISSUE TITLE
TLS as an optional feature

### ISSUE THREAD

**Issue by bbigras** [snapview/tokio-tungstenite#11]
It would be nice to be able to build without TLS. Tungstenite already supports it.

**Comment by application-developer-DA** [comment]
We'll see how to implement this while keeping it transparent and flexible. Once we discussed this topic: https://github.com/snapview/tokio-tungstenite/issues/5#issuecomment-291485932

At the moment I'm not sure if it should be a feature, most likely we need a separate crate with the helper/connector like in `hyper`. We have to be consistent with the existing "conventions" used in tokio. I'll try to check what's the state with `hyper` in this regard and probably talk to Alex Crichton.

**Comment by application-developer-DA** [comment]
@agalakhov has solved this issue in his latest commits. Check out the new version.

**Comment by flosse** [comment]
> @agalakhov has solved this issue in his latest commits. Check out the new version.

Could you reference a commit? I tried `v0.2.1` but that didn't work :(

**Comment by application-developer-DA** [comment]
`v0.2.1` should already contain the required changes, but you have to use a corresponding function: https://docs.rs/tokio-tungstenite/0.2.1/tokio_tungstenite/fn.connect_async.html

**Comment by flosse** [comment]
...how is `connect_async` related to TLS?

**Comment by agalakhov** [comment]
This is the only function that has something to do with TLS. On a client, just providing a wss:// URL to connect_async() would result in establishing of a TLS connection.

On a server, Tungstenite does not accept connections itself. It only upgrades an existing connection to a websocket one. It is not possible to automatically switch between TLS and plain connections since they use different ports and the TLS one has certificates and even may have SNI, and this is obviously out of the scope of Tungstenite. The server-side code must accept the connection including the proper TLS handshake with correct certificates, if any.

Upgrading an existing connection from other libraries to a websocket one does not require any specific TLS support from Tungstenite. This is only needed for client-side connections that start with an URL.
