### ISSUE TITLE
When we can consider the client connection closed and safe to drop?

### ISSUE THREAD

**Issue by DouglasGray** [snapview/tokio-tungstenite#119]
Hello,

First off, thank you for the awesome library, it's much appreciated! Apologies if this is all documented elsewhere but I couldn't find anything after digging around for a bit, however I've a quick question regarding when we should consider the connection fully closed from the client side and safe to drop. I noticed [here](https://github.com/snapview/tungstenite-rs/pull/56) in the PR for adding the ```Close``` message that it says "_the only concern I have is that the client may receive this message and tear down the connection immediately...So I decided to return the Message::Close for the client when the connection is actually fully closed (after all acknowledgements etc)_", and in the [docs](https://docs.rs/tungstenite/0.11.1/tungstenite/error/enum.Error.html) for the ```ConnectionClosed``` error, it says "_when you receive this, it is safe to drop the underlying connection_". 

So I just wanted to confirm that, for the client, should we expect that both the ```Close``` message and ```ConnectionClosed``` error will appear when the connection closes normally, and just the ```ConnectionClosed``` error when it closes abnormally? And in both cases (either receiving the ```Close``` message or ```ConnectionClosed``` error) I'm ok to drop the connection, no further work on the channel required?

Thanks in advance!

**Comment by application-developer-DA** [comment]
Hi @DouglasGray , when remote peer closes the connection, you will get the `Message::Close` on your side (in case you want to have some special behavior that depends on a close code). After that you will get `ConnectionClosed` which will signify that it's safe to drop the object. In other words: the documentation you referred to is still valid :)

Given that you created this issue in `tokio-tungstenite`, I may assume that you're using `tokio-tungstenite` (not `tungstenite-rs directly)`. I this is the case, then you don't need to worry about `ConnectionClosed`, because this is already handled by `tokio-tungstenite` -- `ConnectionClosed` [is automatically translated to the "end of stream"](https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L289) inside `Stream`'s implementation for the `WebSocketStream`.

**Comment by DouglasGray** [comment]
Great, thank you for clarifying, and knowing that I can just wait for end of stream simplifies my code a bunch. And thanks for the quick reply!
