### ISSUE TITLE
How to handle server-side gzip compression?

### ISSUE THREAD

**Issue by wbrickner** [snapview/tokio-tungstenite#129]
Hello,

I am using this library to connect to a server which pushes thousands of messages per second, each of which is gzipped.
It will only send those messages once I explicitly subscribe, so those are not present.

What I can see are ping messages which are not detected as `Message::Ping` already because the stream is gzipped.

Is this implemented already and I've done something incorrectly? I assume it's not implemented, so how would I go about this?

My thinking is to somehow provide an intermediate processor over the underlying TLS stream and use a GZIP decompressor from crates.io.  Do you have any advice on how I can complete this?

**Comment by wbrickner** [comment]
After a little more digging,  unfortunately what the server devs have done (I think) is send a Binary message (on the layer of the websocket protocol, not sending a binary message directly).  This binary data is gzipped JSON. 

What I think I now have to do is listen for a `Message::Binary` and then decompress into a JSON string.
This is really annoying, because all of the real WebSocket protocol is discarded, and things like a ping are represented as a Binary WebSocket message that decompresses to something like `{"ping": ... }`. 

This is not actually that bad yet, but now I've lost the safety and convenience of getting thing like `Close` results from this library, along with automatic pong sending etc.

My question is: is there any way I can implement some sort of hook into the `tokio-tungstenite` socket to implement this logic and make it seamless? Essentially I want to provide custom logic over the processing of `Message`s before they're emitted.

If not I understand, it's probably unwise to bend over backwards to allow convenience for people who don't actually conform to the WebSocket spec.

**Comment by wbrickner** [comment]
(I also have not yet checked the WebSocket spec, so do not understand how messages are actually represented yet)

As a last hope, could the library be misidentifying these incoming messages as binary messages, and if I were to decompress them before they became available, the lib would handle everything as normal?

**Comment by application-developer-DA** [comment]
Hi, as far as I got it, the issue that you describe does not really require any "hook" in `tokio-tungstenite`. It seems like you're trying to mix several things, let me explain what I mean.

There are several "types" of WebSocket messages that are defined in [RFC 6455](https://tools.ietf.org/html/rfc6455) and [that are supported](https://docs.rs/tungstenite/0.11.1/tungstenite/enum.Message.html) by both `tungstenite` and `tokio-tungstenite`. As long as you use `tokio-tungstenite` you can be sure that you'll get `Close`, `Ping` (and automatic reply with `Pong`) as we enforce the protocol logic as specified in RFC.

In your particular case it seems like you're just sending regular `Binary` WebSocket messages. Each of these messages contains a compressed (gzip) JSON-encoded message. It also seems that you defined your custom "application-level protocol" which sends custom ping messages as WebSocket binary messages (which strictly speaking is ok, it's not prohibited by WebSocket protocol itself), i.e. you don't rely on pings from WebSocket protocol, but have your own idea of pings. This is totally fine and you can still use it like this, but I think that your expectation was that `tokio-tungstenite` would automatically turn the "custom messages" into WebSocket's `Ping` messages, which actually does not happen (and must not happen in fact).


> My thinking is to somehow provide an intermediate processor over the underlying TLS stream and use a GZIP decompressor from crates.io. Do you have any advice on how I can complete this?

This is quite trivial in fact. `WebSocketStream` [is a `Stream` of WebSocket messages](https://docs.rs/tokio-tungstenite/0.11.0/tokio_tungstenite/struct.WebSocketStream.html#impl-Stream). You can just map that stream and write any sort of processing of these messages so that you transform a stream of WebSocket messages to the stream of your custom-made messages containing the application logic. You may be interested in examples from the repository [and Tokio docs](https://tokio.rs/) to properly implement it.


> This is not actually that bad yet, but now I've lost the safety and convenience of getting thing like Close results from this library, along with automatic pong sending etc.

You will still observe all `Ping` and `Close` messages as long as we're talking about WebSocket's close and ping. In case you send some custom `Binary` message, which has something like `{ "action": "close", ... }`, then of course it won't be turned into WebSocket's `Close` message automatically (and in fact it must not be done as it would violate the RFC). But you can write any application level logic on top of `tokio-tungstenite`.

```
ws_stream.map(handle_message).for_each(|your_message| {
})
```

I.e. you just need a function that maps `tungstenite::Message` to `yourownproject::Message`.

**Comment by wbrickner** [comment]
Thank you, I ended up solving the issue an uglier way because I couldn't find a way to process the stream neatly, I will look into the methods you have provided for a cleaner implementation, although it may come at a performance penalty because I think I may have trouble capturing long-lived buffers for decompression work and would like to avoid reallocation costs. The way I have done it is to spawn a Tokio task, and inside the task allocate your buffer which will stick around for the lifetime of the connection, etc. 

To avoid public embarrassment (in an interaction with someone famous!), this sort of spec-violating nonsense is not something I implemented server-side, it is my misfortune to be the consumer a weird WS API.

Thank you for all your help!
