### ISSUE TITLE
Implement `tokio::io::split` for `WebSocketStream`

### ISSUE THREAD

**Issue by PragmaTwice** [snapview/tokio-tungstenite#144]
For now, `WebSocketStream` can be `split` by `futures::util::stream::StreamExt` to `(SplitSink, SplitStream)`.
But in `tokio`, all `split` (by `tokio::io::split`) for stream lead to `(ReadHalf, WriteHalf)`.
Is there a plan to unify them?

**Comment by application-developer-DA** [comment]
It seems like these are just slightly different (correct me if I'm wrong). Our `WebSocketStream` is neither `AsyncRead`, nor `AsyncWrite`, but implements the `Stream` and `Sink` traits if the underlying stream that we wrap (i.e. the TCP stream or TLS stream) is `AsyncRead` / `AsyncWrite`.

As far as I can see we can't make the `WebSocketStream` to be `AsyncRead` or `AsyncWrite` by itself, because it will change the usage semantics of it, i.e. "bypassing" / "ignoring" the logic encapsulated inside it WebSocket. `AsyncRead` and `AsyncWrite` are just too generic. I believe they are meant to be implemented by "byte streams", whereas we try to yield the stream of messages.

**Comment by sdroege** [comment]
You could use https://crates.io/crates/ws_stream_tungstenite if you want a stream-based (`AsyncRead` / `AsyncWrite`) interface on top of a websocket, but generally for the websocket protocol that makes not much sense.
