### ISSUE TITLE
Build with --no-default-features fails

### ISSUE THREAD

**Issue by Johannesd3** [snapview/tokio-tungstenite#154]
Compilation with `--no-default-features` does not work:
```
$ cargo build --no-default-features
   Compiling tokio-tungstenite v0.13.0
error: unused import: `Request`
  --> src/lib.rs:40:35
   |
40 |         client::{ClientHandshake, Request, Response},
   |                                   ^^^^^^^
   |
note: the lint level is defined here
  --> src/lib.rs:11:52
   |
11 | #![deny(missing_docs, unused_must_use, unused_mut, unused_imports, unused_import_braces)]
   |                                                    ^^^^^^^^^^^^^^

error: aborting due to previous error

error: could not compile `tokio-tungstenite`
```
This happens ever since release 0.10.0, seems as if no one's complaining.

**Comment by strohel** [comment]
I would guess this only happens if you build `tokio-tungstenite` without default features _directly_. If `tokio-tungstenite` is built as part of a dependency chain, my tip is that cargo will limit these `#![deny` statements. Could you please confirm?

It doesn't change the fact that it should be fixed (and added to CI to stay fixed). Would you like to contribute? Seems to be as easy as making the import either conditional, or moving it, or adding and `#allow[` - whatever is clearer.
