### ISSUE TITLE
WebSocketStream::poll_ready returns Ok(()) even when closed

### ISSUE THREAD

**Issue by koivunej** [snapview/tokio-tungstenite#160]
I was just testing the client side out with an older version (0.11) and noticed that after the `Stream::poll_next` returning a `None` (for server closed websocket) the `poll_ready` kept returning `Ok(())`. Looking at the latest version it'd seem that most of the behaviour is the same. I'm thinking that the `poll_ready` should start returning an error as soon as all pending writes have completed and the connection has closed and thus the closing is ready.

I was thinking the `poll_ready` might be needed to kept called so that the last write can be flushed out. This flushed out message would be the reply queued in the [`tungstenite::...::WebSocketContext::do_close`](https://github.com/snapview/tungstenite-rs/blob/e6fee8972605d8e6a3cd23db5826a5fb8b14beb5/src/protocol/mod.rs#L576) as far as I understand.

From wireshark it looked like the `poll_ready` continued to return `Ok(())` even if the underlying tcp connection was closed.

I did try to look up older issues but couldn't see one. Please feel free to redirect me if I missed one and not start rehashing if this has been covered already.

**Comment by application-developer-DA** [comment]
> I was just testing the client side out with an older version (0.11) and noticed that after the Stream::poll_next returning a None

We return `None` from the `Stream` once the connection has been closed.


> I was thinking the poll_ready might be needed to kept called so that the last write can be flushed out. 

If the `Stream` returned `None`, then the connection has already been closed, so there is nothing to flush ;) The thing is that the underlying implementation of the `read_message()` that is called by a `Stream` not only performs read, but also writes to the socket (this is required to uphold some WebSocket invariants described in RFC that include but not limited by things like replying with to ping message with a pong etc).

The reason `Sink::poll_ready()` returns `Ok(())` might be because of it calling `write_pending()` which in turn [sees that the connection is closed](https://github.com/snapview/tungstenite-rs/blob/e6fee8972605d8e6a3cd23db5826a5fb8b14beb5/src/protocol/mod.rs#L390) and just returns `Ok(())`. Calling `write_message()` (that calls `write_pending()` to "drive" the write till completion) would on the other side return an error, because writing to the closed socket is forbidden.

So once you get `None` from the `Stream`, it's safe to drop the connection. `tungstenite-rs` would return `ConnectionClosed` and `AlreadyClosed` when `read_message()` is called. These are exactly the values that we [map to `None` for Tokio](https://github.com/snapview/tokio-tungstenite/blob/master/src/lib.rs#L274).

**Comment by koivunej** [comment]
Thanks for quick reply and the explanation which makes sense. It would seem that I had missed that the read_message() can also drive the sending of the reply in question to completion before `None` gets returned from the `Stream::poll_next` so this is good to close.
