### ISSUE TITLE
connect_async failing where tungstenite::connect does not.

### ISSUE THREAD

**Issue by willdoescode** [snapview/tokio-tungstenite#166]
Getting http status 400 when using connect_async when using tungstenite::connect with the exact same url I do not get a http status 400.

**Comment by application-developer-DA** [comment]
We're not going to be able to help without any further information or steps that could help to reproduce the issue.

Are you sure that you have TLS features enabled and that it's not due to the TLS?

**Comment by runapp** [comment]
BTW is silent fallback the expected behaviour if none of tls-related feature is enabled, while connecting to secure websockets? It did take some time for me to find the cause today.

Actually, I did enabled the `tls` feature, though after recent update this feature is splited up, and I didn't noticed it and just disabled `tls` feature. I'm not sure that if there was an warn or something for not enableing these feature before the update?

**Comment by application-developer-DA** [comment]
Well, we have added some notes about the `tls` in our `README` as it indeed was a common mistake for people (to forget enabling TLS).

**Comment by runapp** [comment]
Okay, just hope that's enough for it... Checking url scheme at runtime do have cost.

**Comment by application-developer-DA** [comment]
Yeah, but it was not only about the URL, but also because AFAICR the guy who submitted the PR raised a good point that it's probably up to the caller / application developer to select which TLS implementation she wants to use as a dependency as it may have some implications (i.e. link to OpenSSL or use the `rustls` etc).

**Comment by runapp** [comment]
Exactly, and I think the key is whether to add a warn when `wss://` is used and none of the tls features are enabled? The drawback is adding a small overhead at runtime, to check the scheme if none of the tls feature is enabled.
