### ISSUE TITLE
Is it safe to use select! with WebSocketStream?

### ISSUE THREAD

**Issue by gsserge** [snapview/tokio-tungstenite#167]
The interval server example demonstrates a pretty useful pattern using `select!` macro https://github.com/snapview/tokio-tungstenite/blob/master/examples/interval-server.rs#L26

I was wondering though if it's safe to use it like that given that `select!` will drop futures from the arms that did not complete. For example, if the tick happens while a new message is being read from the tcp stream, wouldn't the message be dropped?

**Comment by application-developer-DA** [comment]
It is safe to use otherwise it would have probably been an `unsafe` function :) It's up to the caller to implement the desired logic though. `select!` is merely a syntax sugar wrapper around a construction that polls both futures and executes the given block once one of the future completes. The `ws_receiver` is just a split part (read part) of the stream, so it stores the state internally. The message frame is accumulated in the internal buffer and once it's ready the message is returned to the user. Hope this helps ;)
