### ISSUE TITLE
Is it possible to set proxy for WebSocket connections?

### ISSUE THREAD

**Issue by runapp** [snapview/tokio-tungstenite#168]
Inspecting raw stream content is always helpful when debugging, especially for connection problems. But I found there's no way to set proxy for connection, neither does `http(s)_proxy` env take effect.
Am I missing something, or it's currently not supported? And will this feature ever be added to this crate?

**Comment by application-developer-DA** [comment]
Currently our library does not implement any specific proxy support, but there is a tracking issue for that: https://github.com/snapview/tungstenite-rs/issues/177

The idea was that we find some decent library that deals with proxy related logic and "integrate" it in `tungstenite-rs` as a feature (we don't want to code "our own" support  for proxies as it would mean that we're not only designing a library for WebSockets, but instead do some sort of a web-framework which is not a purpose of `tungstenite-rs` since there are other things like `warp` that rely on `tungstenite-rs` / `tokio-tungstenite` for WebSocket support).

I'm going to close this particular issue as duplicate, feel free to continue discussion in the above mentioned issue ;)
