### ISSUE TITLE
Allow passing configs to respective tls libraries

### ISSUE THREAD

**Issue by sethwheway** [snapview/tokio-tungstenite#180]
Please correct me if I'm wrong, but from what I can tell, there is no way to have any control over the operations of the libraries used for tls connections for a client. This seems like a major missing feature. This is especially tricky to work around now the `tls` module as been made private.
Providing a high level API over configuration of these libraries is probably out of the scope of this project, however being able to pass the respective config struct of each library to a `connect_async` like function would be very helpful for some use cases.

**Comment by application-developer-DA** [comment]
There is a possibility to control which TLS implementation is going to be used, it's [part of the features](https://github.com/snapview/tokio-tungstenite/blob/master/Cargo.toml#L17). There is however not much control w.r.t. details of the TLS implementation (no access to the `TlsBuilder` etc), i.e. if you want something like [this](https://github.com/snapview/tungstenite-rs/issues/203), then it's not yet implemented on the `tokio-tungstenite` or `tungstenite-rs` level.

We did not have a goal [initially] to support it, so that we don't extend the scope of the `tokio-tungstenite` by too much. The main reason was that actually it's possible to connect to the instance using TLS directly and then passing the resulted stream to the `tokio-tungstenite`, i.e. if someone wants a very fine-grained control over the TLS, there's always a possibility to do it in a user code and pass the TLS stream to the `tokio-tungstenite`.

**Comment by eminence** [comment]
In my code, I needed a way to install custom root certificates, which required detailed TLS control (as well as passing in some customer headers).  Here's how I did it with tokio-tungstenite, in case it helps anyone else:

```rust
let tls = native_tls::TlsConnector::builder()
    .add_root_certificate(native_tls::Certificate::from_pem(include_bytes!("../chain1.pem")).unwrap())
    .add_root_certificate(native_tls::Certificate::from_pem(include_bytes!("../chain2.pem")).unwrap())
    .build()?;
let connector = tokio_tungstenite::Connector::NativeTls(tls);

let addr = "example.com:443";
let socket = tokio::net::TcpStream::connect(addr).await?;

let mut headers = Vec::new();
headers.push(httparse::Header {
    name: "Cookie",
    value: cookies.as_bytes(),
});

let request = httparse::Request {
    method: Some("GET"),
    path: Some("wss://example.com/endpoint.ws"),
    version: Some(1),
    headers: &mut headers,
};

let ws = tokio_tungstenite::client_async_tls_with_config(request, socket, None, Some(connector)).await?;
```

It's pretty verbose, but it works 🎉

**Comment by application-developer-DA** [comment]
Yep, so the TLS part can't be simplified much I believe. It's also similar to the https://github.com/snapview/tungstenite-rs/pull/226 that was recently added to the `tungstenite-rs`.

So I'm going to close this issue, but let me know if I'm missing on something or misunderstood the issue (and feel free to re-open then).

**Comment by zjsec** [comment]
share my code to help others.
```Rust
static ROOT_CERT: &[u8] = include_bytes!("../conf/root-ca.crt");

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // request
    let url = Url::parse("wss://127.0.0.1:12345/123")?;
    let mut req = url.into_client_request()?;
    req.headers_mut()
        .insert("Authorization", HeaderValue::from_str("Bearer [token]")?);

    // connector
    let tls_connector = native_tls::TlsConnector::builder()
        .add_root_certificate(native_tls::Certificate::from_pem(ROOT_CERT)?)
        .build()?;
    let connector = Connector::NativeTls(tls_connector);

    // connect
    let (ws_stream, response) = connect_async_tls_with_config(req, None, Some(connector)).await?;

    ......

    Ok(())
}
```
