### ISSUE TITLE
wss:// connections silently downgrade to plaintext if tokio-tungstenite is not compiled with TLS support

### ISSUE THREAD

**Issue by haileys** [snapview/tokio-tungstenite#182]
If the url scheme is `wss`, tokio-tungstenite will always [connect to port 443](https://github.com/snapview/tokio-tungstenite/blob/2546fa0443f06e2b4cad52529d4feafa79e39d88/src/connect.rs#L38), regardless of the presence of TLS support. However, if TLS support is not compiled in, tokio-tungstenite will speak plaintext over port 443.

This leads to hard-to-debug errors where a server may respond with `HTTP 400` (this is the behaviour I have observed in nginx). tokio-tungstenite should instead refuse to connect to `wss://` URLs if no TLS support is compiled in and return an error.

**Comment by haileysome** [comment]
It appears that returning an error rather than downgrading to plaintext may actually be the intended behaviour: https://github.com/snapview/tokio-tungstenite/blob/2546fa0443f06e2b4cad52529d4feafa79e39d88/src/tls.rs#L123

However this seems to be foiled by the compile-time conditional dispatch in `connect_async_with_config`: https://github.com/snapview/tokio-tungstenite/blob/2546fa0443f06e2b4cad52529d4feafa79e39d88/src/connect.rs#L48-L56
