### ISSUE TITLE
Question about buffering for outgoing messages

### ISSUE THREAD

**Issue by chameleon6** [snapview/tokio-tungstenite#191]
Can someone explain how the buffering works for outgoing messages? Awaiting on a call to WebSocketStream::send(...) does not block even after 10k messages in rapid succession, so there is clearly some buffering going on. However, changing max_send_queue to 1 WebSocketConfig still doesn't cause any "buffer full" errors, so I'm unsure if this is happening at the WS or TCP level.

My end goal is to understand the logic for buffering, in particular is it based on some small wait time, buffer size, or both? I seem to lack the understanding to figure this out from log messages, so any pointers to locations in the code, keywords, or articles would be helpful. Thanks!

**Comment by application-developer-DA** [comment]
The buffering work as follows: whenever you try to send a message, we add it to the queue and try to write it to the socket if the socket is not busy. I.e. if we see that the socket returns `EWOULDBLOCK`, we know that we can't start writing the message to the socket, so the message remains in the sending queue up until we notice that the socket is ready and we can write something to it. The size of this send queue is the `max_send_queue`.

If you set the queue size to `1` and still don't get any `SendQueueFull` errors, then it only means that the messages are able to be written fast without blocking the socket, i.e. they don't buffer on the `tungstenite-rs` and so the send queue does not grow over the size that you specified.

Here is the corresponding part in the code: https://github.com/snapview/tungstenite-rs/blob/master/src/protocol/mod.rs#L337

Hope this helps!

**Comment by jeff-chameleon-trading** [comment]
Thanks for the detailed response! 

Just to confirm my understanding, the TCP implementation under the hood still may involve some buffering, just that it's hidden from the perspective of the code in this crate?

**Comment by injecto** [comment]
The provided code contains `write_pending` call, that internally does

```
while let Some(data) = self.send_queue.pop_front() {
    self.send_one_frame(stream, data)?;
}
```
Does it mean that on every input message, the library will try to flush ALL the queue instead of, for example, just make a place for the single message? It looks like the queue is senseless here.

**Comment by application-developer-DA** [comment]
`write_pending()` tries to write the messages to the socket up until it receives an error or `EWOULDBLOCK`.

> It looks like the queue is senseless here.

Why do you think so?

The queue is required to queue up multiple messages for sending. In certain circumstances it's required, e.g. when we receive certain messages such as `Close`, we must reply to them by sending a certain response (as per RFC) back, e.g. queue them up. Also, nothing speaks against e.g. calling `write_message()` 10 times in a row to queue up the messages. Without the queue, such things would not have been possible. I.e. imagine we have no queue, you call a `write_message()`, it tries to write the message to the socket, but gets `EWOULDBLOCK`, where do we store the part that has not yet been written? We would need to store it anyway. Or what if you call `write_message()` right after the `EWOULDBLOCK` 3 times in a row? - The socket is busy and we can't write to it, so we would have to return an error in all such cases, giving the message back to the user. In other words: we would anyway need require a queue, unless we decided to put the responsibility for sticking with the RFC on the shoulders of user and document that they must reply to `Ping` in a certain way, must react to `Close` in a certain way and must call `write_pending()` with a buffer that `write_message()` returns to them in case the message was only partially written forcing them to use exactly the returned "not fully written" part etc. This would make library pointless.

**Comment by injecto** [comment]
> write_pending() tries to write the messages to the socket up until it receives an error or EWOULDBLOCK.

Unfortunately, I still can't get this idea. I see the code:

```
impl<T> Sink<Message> for WebSocketStream<T>
where
    T: AsyncRead + AsyncWrite + Unpin,
{
    type Error = WsError;

    fn poll_ready(mut self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Result<(), Self::Error>> {
        (*self).with_context(Some((ContextWaker::Write, cx)), |s| cvt(s.write_pending()))
    }
```

`cvt()` returns `Poll::Pending` on `WouldBlock`, so it leads to polling the future till the full queue flush. Or am I missing something?

Thanks for explanations in advance.

**Comment by application-developer-DA** [comment]
Ah, now I see what you mean. You're concerned about the implementation of the `Sink` for the `WebSocketStream` where the `poll_ready()` does not flush only one message, but instead flushes all of them, right? - If so, then yes, your assumption is correct: the current implementation of the `Sink::poll_ready()` is identical to the implementation of the `Sink::poll_flush()` in our case.

E.g. if you want to re-use the `tungstenite`'s logic for buffering in such cases, it would probably be a better idea to use something like `SinkExt::send_all` instead of a `SinkExt::send`.

We could in theory make the `poll_ready()` to only check the queue size and return an error, but I'm not sure it would solve the "problem" in question since things like `SinkExt::send` would anyway call the `Sink::poll_flush` once the message is sent. Also it means that the users won't be able to `forward()` the stream to the sink that easily since they may encounter the error telling that the buffer is full. Also the question is how the `Forward` would behave (I have not checked it in detail to be honest due to the `delegate_all` macro the meaning of which I did not "decode" back then when we checked the PR introducing the migration to the newest Tokio 🙂). If `Forward` future would only call `Sink::poll_flush` once the `stream` is exhausted, it would cause a big problem of messages not being delivered and waiting into a queue, since no one drives their sending till the completion until. If it however calls the `Sink::poll_flush` after each message on the stream sent to the sink, then it won't make a difference to the current implementation as well.

E.g. it means that if you really want to "re-use" the original queue logic from `tungstenite` and let the messages buffer on the queue when you send multiple of them in a row, then using something like `SinkExt::send_all` seems like one of the available options. Otherwise you could call `start_send` a couple times in a row in your code and start flushing them once you queued them up (e.g. call `poll_ready()`, then call `start_send` multiple times in a row, which would require you to handle the error in case the queue is full and the message is returned though).

**Comment by injecto** [comment]
Thank you for the detailed explanation of what was behind the motivation of the current `poll_ready` implementation. So I'll introduce my own queue atop of it.
