### ISSUE TITLE
Potential memory leak on sender?

### ISSUE THREAD

**Issue by Lighty0410** [snapview/tokio-tungstenite#195]
Hey everyone. First of all, thank you a lot for this amazing repo. (excuse me if it's a duplicate of [this](https://github.com/snapview/tungstenite-rs/issues/237) . I'm not completely sure where this issue belongs to).

The issue: 
I need to send binary data across clients. Each time a client connects to the websocket i accept the connection and start sending binary data to them without any bidirectional signal. And here comes the problems. The pipeline: 
1) Accept the connection. 
2) Start sending binary messages to the receiver. 
3) Resident memory of the application has grown by like ~50kb. 
4) Client closes the application on his side without any signaling with, for example, SIGINT (for some reason, i don' think signaling is the case).
5) The tokio task is over. 
6) However, resident memory consumption remains the same. After the client has disconnected there's NO expected resident memory usage dropdown. It seems like a certain buffer doesn't truncate (just an assumption).
 7) Repeat these steps and see how the application uses more and more memory (until OOM killer wouldn't kill it). 
 
 At first, i thought maybe there's some buffered info in the TCP sock. I tried to close the `ws_stream` using `.close()`. I tried to shut down the connection via `.get_mut().shutdown()`. Neither of them does anything, and both of them return all the same error - "broken pipe". At second i thought it's the allocator that doesn't return memory to OS. So i switched to jemalloc with some aggressive tuning and waited for almost an hour. 
 
 How i tested this behavior: 
 1) Run the [sender](https://gist.github.com/Lighty0410/f39980b34e67b6e775e4c1b13264dd01)
 2) Run the [receiver](https://gist.github.com/Lighty0410/842c35e0a3bfc9ecc739cf6b5680d72e)
 3) Optionaly apply aggressive tuning for jemalloc - `JEMALLOC_SYS_WITH_MALLOC_CONF="background_thread:true,narenas:1,tcache:false,dirty_decay_ms:0,muzzy_decay_ms:0,abort_conf:true"`
4) Open htop.
5) Kill and run the receiver multiple times. 
6) Witness how the sender uses more and more memory while you repeat step 5. 

The question is. Is there anything wrong with the examples above ? Or i missed something ? 
Thanks in advance!

**Comment by application-developer-DA** [comment]
Hi,

no, it's not a memory leak in `tungstenite` or `tokio-tungstenite`. We do have an internal queue of messages ([that can be configured](https://docs.rs/tungstenite/0.15.0/tungstenite/protocol/struct.WebSocketConfig.html#structfield.max_send_queue)), but the queue along with all other resources is released once the object is dropped (once the corresponding task is over).

I had a quick look at the code that you shared and I think the problem is with way you use the `tokio::sync::broadcast`. What must have happened is something like this: the `broadcast::channel`'s queue is being filled up pretty quick as the values are pushed every 5 milliseconds. Since the clients appear and get killed constantly but at a slower rate, each `Receiver` gets a cloned copy of the messages that it wants to retain. But since the queue is filled up pretty quickly, clients [start to lag returning `RecvError::Lagged`](https://docs.rs/tokio/1.12.0/tokio/sync/broadcast/index.html#lagging),. While they are doing so, the task for the particular client is still alive and consumes resources (which with the increasing amount of connections creates an impression of the memory leak). In addition to that each receiver will get a cloned copy of the value that you sent to the `channel` which will grow linearly by the amount of receivers. So at the end we end up in a situation that the `queue` is always filled up and the clients are lagging almost constantly only consuming resources.

**Comment by Lighty0410** [comment]
> 
> 
> Hi,
> 
> no, it's not a memory leak in `tungstenite` or `tokio-tungstenite`. We do have an internal queue of messages ([that can be configured](https://docs.rs/tungstenite/0.15.0/tungstenite/protocol/struct.WebSocketConfig.html#structfield.max_send_queue)), but the queue along with all other resources is released once the object is dropped (once the corresponding task is over).
> 
> I had a quick look at the code that you shared and I think the problem is with the way you use the `tokio::sync::broadcast`. What must have happened is something similar to this: the `broadcast::channel`'s queue is being filled up pretty quick as the values are pushed every 5 milliseconds. Since the clients appear and get killed constantly but at a slower rate, each `Receiver` gets a cloned copy of the messages that it wants to retain. But since the queue is filled up pretty quickly, clients [start to lag returning `RecvError::Lagged`](https://docs.rs/tokio/1.12.0/tokio/sync/broadcast/index.html#lagging). While they are doing so, the task for the particular client is still alive and consumes resources (which with the increasing amount of connections creates an illusion of the memory leak). So each receiver [will get a cloned copy](https://docs.rs/tokio/1.12.0/tokio/sync/broadcast/index.html#) of the value that you sent to the `broadcast::channel` which will grow linearly by the amount of receivers. So at the end we end up in a situation that the `broadcast::channel` is always filled up and the clients are lagging almost all the time only consuming resources.

Indeed it's not the websocket connection issue :). Something weird's going on with the broadcast's receiver. It's not lagging, but doesn't return memory to OS when the receiver's dropped. But it's another topic of discussion and it's completely unrelated to this issue. 
Closing the issue. 
Thank you !

**Comment by mmalmi** [comment]
@Lighty0410 did you find a solution to this? I'm having the same issue in my project: https://github.com/mmalmi/gun-rs/blob/cab1059e62bd35e1d9281c623445b2bb978e0b66/src/adapters/websocket_server.rs#L115
