### ISSUE TITLE
Correct the examples so that they compile

### ISSUE THREAD

**Issue by MathieuDutSik** [snapview/tokio-tungstenite#201]
For example, the client.rs file does not compile.
Also, provide Cargo.toml files to make sure that dependencies are clear.

**Comment by jxs** [comment]
Hi, and thanks for the interest! You can successfully run and compile the client example with:
`cargo run --example client -- ws://localhost:12345/` assuming you are running the [server example](https://github.com/snapview/tokio-tungstenite/blob/master/examples/server.rs#L13). Regarding `Cargo.toml`  you can check the dependencies on the [`[dev-dependencies]` section](https://github.com/snapview/tokio-tungstenite/blob/master/Cargo.toml#L66-L70).

We probably could improve the client example with usage instructions though, would you like to give it a go?

**Comment by RonaldColyar** [comment]
Seems I've ran into similar issues trying to run the client/server example locally using cargo.

```
 cargo run --example server 127.0.0.1:12345
    Updating crates.io index
error: failed to select a version for the requirement `rustls = "^0.20.0"`
candidate versions found which didn't match: 0.19.1, 0.19.0, 0.18.1, ...
location searched: crates.io index
required by package `tokio-tungstenite v0.16.1
```

**Comment by application-developer-DA** [comment]
As @jxs mentioned, the example compile well and the dependencies are part of the `[dev-dependencies]`, so that there is nothing we can really "correct" in the examples themselves. Perhaps we could have explicitly mentioned in the `README` (or each particular example) how the `Cargo.toml` would look like, but it would get too cumbersome to keep up-to-date due to the need to synchronize the `[dev-dependencies]` with each particular example. 

So I think I'm going to close this one. But if you have another opinion or would like to submit the PR, then of-course we would look into that ;)

**Comment by RonaldColyar** [comment]
When one takes a look at the example files `server.rs` and `example.rs` it says 


 You can test this out by running:
     cargo run --example server 127.0.0.1:12345

And then in another window run:
   cargo run --example client ws://127.0.0.1:12345/
   
   
This leads me to believe these examples could be compiled and executed with just those two steps. 

It is just a comment but it is a bit misleading, I would be happy to submit a pull request editing that comment or adding a readme with the actual steps.

**Comment by application-developer-DA** [comment]
> And then in another window run:
> cargo run --example client ws://127.0.0.1:12345/
>
> This leads me to believe these examples could be compiled and executed with just those two steps.

This is a correct reasoning 🙂 But does it not compile successfully? I've just tried to execute exactly this command and it compiled without any errors.
