### ISSUE TITLE
the dependencie of tungstenite has released a new version，wish to publish a follower version

### ISSUE THREAD

**Issue by aa51513** [snapview/tokio-tungstenite#209]
the newest version of tungstenite is v0.17.1
which allows to specify the host parameter

Special Note: This is a compatible new version and will not cause compatibility issues
will a new version be released to follow ?

**Comment by application-developer-DA** [comment]
The new version could be published in the following days.

It's not fully backward-compatible with the older version due to the change in the behavior of how the user's requests (headers etc) are processed, [please check the changelog](https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md#0170) for more information. However, if you never passed custom `Request`s to the library, then it's perfectly backward-compatible (hope I got your question right).
