### ISSUE TITLE
"Bad device type." in examples/client.exe under wine

### ISSUE THREAD

**Issue by Sfinx** [snapview/tokio-tungstenite#213]
Stock Ubuntu 20.04, latest rustup, while trying to run the client example from tokio-tungstenite under wine getting this:

```
thread 'main' panicked at 'Failed to connect: Io(Os { code: 66, kind: Uncategorized, message: "Bad device type." })', examples/client.rs:29:51
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Tried winehq-7.0 (stable), winehq-7.2 (dev & staging). ping & DNS works ok from wineconsole

BTW: Backtrace is empty even when "full". I'm building using cross from linux.

What can be the problem ? How to debug ?

**Comment by Sfinx** [comment]
Seems like did not catch the real issue - tungstenite-rs _works_ with rustls under wine but tokio-tungstenite _do_not

**Comment by agalakhov** [comment]
This depends on the environment, not on the library. Small differences in the initialization result in completely different TLS behavior.

**Comment by application-developer-DA** [comment]
> works with rustls under wine but tokio-tungstenite _do_not

This is because `tokio-tungstenite` is a version that runs in "`tokio` environment". E.g. `tungstenite` is a simple "core" that merely connects to the host and runs the WebSocket over it. Tokio has its own runtime and its own libraries. I bet you would get the same issue if you just used `tokio-native-tls` or `tokio-rustls`.

The fact that `tungstenite` worked for you with `rustls` only shows that it has nothing to do with the WebSocket logic.  What I want to say is that we can't really solve the problem on our end here (at least based on the current information that we have), because the issue that you're experiencing is outside of what the crate does, e.g. it's on a different level (not on a WebSocket level). The issue is triggered by one of the underlying crates that does not seem to run in your wine environment.
