### ISSUE TITLE
Holding one connection for multiple request from a user

### ISSUE THREAD

**Issue by Relrin** [snapview/tokio-tungstenite#22]
Hello!
I'm trying to figure out with writing my own server with this crate and if I'm doing like in the code below:
```rust
pub struct Proxy {
    router: Box<Router>,
}

impl Proxy {
    pub fn new(router: Box<Router>) -> Proxy {
        Proxy {
            router: router
        }
    }

    pub fn run(&self, address: SocketAddr) {
        let mut core = Core::new().unwrap();
        let handle = core.handle();
        let socket = TcpListener::bind(&address, &handle).unwrap();
        println!("Listening on: {}", address);

        // The server loop.
        let server = socket.incoming().for_each(|(stream, addr)| {
            let handle_inner = handle.clone();

            // Handler per each connection.
            accept_async(stream).and_then(move |ws_stream| {
                println!("Checking the user's token");
                Ok(ws_stream)
            }).for_each(|ws_stream| {  // <--- Handling each incoming message separately?
                println!("Processing...");
                Ok(())
            })
        });

        // Run the server
        core.run(server).unwrap();
    }
}
```
Then getting the following error:
```
relrin at relrin in ~/Code/pathfinder/pathfinder exited 101 on git:master+ 
=> cargo run -- -c ./tests/files/config_with_valid_endpoints.yaml 
   Compiling pathfinder v0.1.0 (file:///home/relrin/Code/pathfinder/pathfinder)
error[E0599]: no method named `for_each` found for type `futures::AndThen<tokio_tungstenite::AcceptAsync<tokio_core::net::TcpStream, tungstenite::handshake::server::NoCallback>, std::result::Result<tokio_tungstenite::WebSocketStream<tokio_core::net::TcpStream>, tungstenite::Error>, [closure@src/proxy.rs:38:43: 41:14]>` in the current scope
  --> src/proxy.rs:41:16
   |
41 |             }).for_each(|ws_stream| {
   |                ^^^^^^^^
   |
   = note: the method `for_each` exists but the following trait bounds were not satisfied:
           `futures::AndThen<tokio_tungstenite::AcceptAsync<tokio_core::net::TcpStream, tungstenite::handshake::server::NoCallback>, std::result::Result<tokio_tungstenite::WebSocketStream<tokio_core::net::TcpStream>, tungstenite::Error>, [closure@src/proxy.rs:38:43: 41:14]> : futures::Stream`
           `futures::AndThen<tokio_tungstenite::AcceptAsync<tokio_core::net::TcpStream, tungstenite::handshake::server::NoCallback>, std::result::Result<tokio_tungstenite::WebSocketStream<tokio_core::net::TcpStream>, tungstenite::Error>, [closure@src/proxy.rs:38:43: 41:14]> : std::iter::Iterator`

error: aborting due to previous error
```
So, my question here is how to make this case possible for using/implementing on the server-side? As far as I understand, the tokio-tungstenite crate don't let me to work at this way, because it presuming that one connection is equal one message, right? 
It will be great, when the server can hold the connection with the client and will processing as much as possible message from him until he will disconnected manually (or server closed it).

**Comment by agalakhov** [comment]
Yes. Your problem is nothing but a coding error: you try to iterate over the result of your `and_then` (which is, in fact, `Result<_>`). The correct core is
```rust
        let server = socket.incoming().map_err(|e| e.into()).for_each(|(stream, addr)| {
            let handle_inner = handle.clone();

            // Handler per each connection.
            accept_async(stream).and_then(move |ws_stream| {
                println!("Checking the user's token");
                Ok(ws_stream)
            }).and_then(|ws_stream| {
                ws_stream.for_each(|ws_stream| {
                    println!("Processing...");
                    Ok(())
                })
            })
        });
```

**Comment by application-developer-DA** [comment]
> As far as I understand, the tokio-tungstenite crate don't let me to work at this way, because it presuming that one connection is equal one message, right?

Of course no, that would be ridiculous :) You can pass as many messages as you want to one WebSocket connection, likewise you can handle as many messages as needed from each WebSocket connection (from each client).

Your code did not compile, because you made a mistake in your code, as mentioned by @agalakhov.

Also feel free to browse through the examples section, it contains a couple of examples for the most common use cases (including the server use case you described above, with some additional common features such as the ability to send messages upon message handling if needed).

**Comment by Relrin** [comment]
Thanks for a detailed answers!
So, now the next thing, with which I'm trying to deal with is that server is closing the connection after handshake, so that I couldn't send a message after it, when otherwise I'm expecting that it won't be closed until happens something wrong. Here is current code:

```rust
impl Proxy {
    pub fn new(router: Box<Router>) -> Proxy {
        Proxy {
            router: router
        }
    }

    pub fn run(&self, address: SocketAddr) {
        let mut core = Core::new().unwrap();
        let handle = core.handle();
        let socket = TcpListener::bind(&address, &handle).unwrap();
        println!("Listening on: {}", address);

        // The server loop.
        let server = socket.incoming().for_each(|(stream, addr)| {
            let handle_inner = handle.clone();

            // Handler per each connection.
            accept_async(stream)
                .and_then(move |ws_stream| {
                    println!("Checking the user's token");
                    Ok(ws_stream)
                })
                .and_then(move |ws_stream| {
                    println!("Processing...");
                    ws_stream.for_each(|ws_stream| {
                        Ok(())
                    });

                    Ok(())
                }).map_err(|err| {
                    println!("Occurred error during the WebSocket handshake: {}", err);
                    Error::new(ErrorKind::Other, err)
                })
        });

        // Run the server
        core.run(server).unwrap();
    }
}
```
Can I somehow hold a connection as much a possible in my case?

**Comment by agalakhov** [comment]
You're doing exactly the same mistake again: `for_each` returns you messages, and the error handler must be related to the inner `for_each`. Please consider reading the documentation for `Future` and `Stream` traits carefully.

**Comment by application-developer-DA** [comment]
1. Yes, sure. Judging from the code, you're not familiar with tokio / futures-rs, don't you? I highly recommend to get familiar at least with some basics as it will help you to write efficient and composable networking code (https://tokio.rs/docs/getting-started/tokio/). Basically all the things you're working here are futures, they are getting polled and "executed" only when you do `run` in the beginning. If you take a closer look at your code, you can see that you construct the `for_each` future (a future which will eventually iterate over websocket messages), and then you effectively drop it, returning `Ok(())`, take a closer look at the code which @agalakhov suggested, you have to return the `ForEach`, so that it's composed with all other futures and can be polled by tokio reactor later on.
2. No, it's not possible, `for_each` itself takes `self`, you cannot split something non-existent inside the `for_each` future (also it would be counterintuitive, as splitting inside`for_each(message)` would allow you to split it again to reading and writing part. You can split the `ws_stream` before `for_each`, I think you can achieve everything with that. The only reason you may want to have an access to `ws_stream` inside `for_each(message)` future is to send responses to the connected client, right? If so, exactly the same use case is covered in our server's example.

**Comment by Relrin** [comment]
Thanks for the answers!
