### ISSUE TITLE
Missing, duplicated or incorrect header sec-websocket-key on mac_os m1 with native_tls

### ISSUE THREAD

**Issue by atmnk** [snapview/tokio-tungstenite#236]
Getting this error when using connect async. This works fine till version 0.16.*

**Comment by application-developer-DA** [comment]
We did [an overhaul of how the request generation works](https://github.com/snapview/tungstenite-rs/blob/master/CHANGELOG.md#0170) in version 0.17 due to the raising demand to customize the request.

If you're using `connect()`, it should work just fine and produce no duplicate or missing headers.

However, the error will occur if you used to construct your request while omitting headers that must be set (previously `tungstenite` would complete the headers with the missing ones and **overwrite some** of your headers). Now the behavior is more consistent:
- If you use `connect()`, `tungstenite` will fill up all headers for you.
- If you create your customer `Request`, `tungstenite` won't try to overwrite your headers, but will accept your request as is pointing out if your request is incorrect (the error that you're getting).

If you want `tungstenite` to create all the headers while being able to customize **some** of them, you could utilize the [`into_client_request` function](https://docs.rs/tungstenite/latest/tungstenite/client/trait.IntoClientRequest.html#tymethod.into_client_request) on a URL that you're trying to connect, followed by changes to the headers that you're willing to change and passing the result to `tungstenite`.
