### ISSUE TITLE
Implementation of server-side "heartbeat"

### ISSUE THREAD

**Issue by Angelin01** [snapview/tokio-tungstenite#241]
This is more of a question than an actual problem, sorry for the issue. Also, please bear with me, I'm new to Rust and, as a first learning projecting, I'm learning all of Rust, Rust Async, Tokio and Websockets (which I've never messed with, even in other languages), so it's all been a bit overwhelming.

I've come to understand that Tungstenite automatically answers Ping messages with a Pong, as per the RFC, and therefore I should not handle it.  
However, I wish to make sure that my clients are still connected and responding and, if I understand correctly, I should use the Ping messages with a payload and expect an immediate response with a Pong message with the same payload. If it fails to arrive, I can "safely" drop the connection as the client is assumed to be non responsive.

As such, I have a few questions:
1. Does it even make sense for the server to do so? Should I just let connections drop and not worry about it? Should I let clients do the heartbeating?
1. Does Tungstenite have any such feature already implemented that I can use? I failed to find references to it, so I believe not.
1. If I must implement it manually, how would one go about doing so? A Tokio task sending Pings every X period? Catching and treating the reply, however, seems a bit complicated with the whole "stream" setup, as they are detached from each other and Tokio's channels tend to make the code flow very much non-linear.

Thanks for the support.

**Comment by application-developer-DA** [comment]
Hey,

1. In general, TCP has a keep-alive mechanism (you can search for keep-alive in our GitHub Issues, there were several issues where I tried to explain the concept 🙂), so in an ideal world you would not need to implement any things, but in reality WebSockets are oftentimes used for the communication that expect to detect client disconnects early instead of waiting minutes or even hours until a broken connection is reported back to the program due to the expiration of keep alive timers (which is also a system-dependant configuration). So it indeed oftentimes useful to implement some sort of a heartbeat where an absent acknowledgement from the client is treated as a connection drop. As to how to implement it, really depends on the use-case and the tolerances that your system has. I.e. some protocols assume that the data is transmitted regularly and lack of data for N milliseconds is treated as a broken pipe.
2. We did not provide any automatic heartbeat logic since it did not seem to be directly related to the WebSocket, but it's easy to implement it on top of the `tokio-tungstenite` and the Tokio framework.
3. Well, it really depends on the task I would say, there are several ways to do it. Assuming that you split the `WebSocket` into stream (reception) and sink (sending) that are handled by separate tasks, you could for instance `match` the message on a stream side when new message arrives and if it's a pong message, you `tx.send(..)` something to the heartbeat channel that you've created in advance. The heartbeat channel could be something like a simple task that is spawned after the WebSocket connection is established and that only does something like this:

(rust-pseudocode)
```rust
// pong sender & receiver
let (tx, rx) = sync::channel()

// pass `tx` into the `read` future later to send pongs over it with `tx.send(..)`
let (read, write) = websocket.split();
[..]


let heartbeat = tokio::spawn(async {
loop {
    match time::timeout(Duration::from_secs(TIMEOUT), rx.recv()) {
        Err(Elapsed) => { // oops, no pong received, terminate the connection },
        Ok(completed) => { // hey, pong received, continue the heartbeat
        Err(SenderDead) => { // websocket connection is dead
            break;
        }
    }
}
});
```

But really there are multiple ways to tackle it :)

**Comment by Angelin01** [comment]
Wonderful explanation, thank you!
