### ISSUE TITLE
Signalr Websocket

### ISSUE THREAD

**Issue by Maidens-jive** [snapview/tokio-tungstenite#244]
According to the SignalR protocol:

All JSON messages must be terminated by the ASCII character 0x1E (record separator).

Is there a setting to configure sending text messages to include the RS character?

**Comment by agalakhov** [comment]
No, this is out of scope of WebSocket library and should be done at JSOn creation time. You can add a small wrapper around Tungstenite, i.e.
```
pub trait SendJson  ̛{
    fn send_json(&mut self, data: impl Serialize) -> Result<...>;
}

impl <T> SendJson for WebSocket<T>
where ...
```

and so on.

**Comment by Maidens-jive** [comment]
I’m a rust newbie.  Not sure I understand how this would work.  Can you help me with more detail of how to implement this?

**Comment by agalakhov** [comment]
What you want is a function that receives JSON and sends it as a message. The convenient way to implement this function is to add it to the WebSocket as a method.

If you're using `tokio-tungstenite`, it is convenient to implement `Sink<YourMessage>` for `WebSocketStream`:
```
impl<T> Sink<YourMessage> for WebSocketStream<T>
where
    WebSocketStream<T>: Sink<Message>,
{
```

and in your implementation just call all corresponding methods from `<Self as Sink<Message>>`. While calling `start_send`, convert `YourMessage` to `Message`. The `YourMessage` struct must be defined by you in order to be able to implement the trait.

If you're using raw Tunstenite, then just add a method to the WebSocket struct that sends `YourMessage`. To do that you have to create some trait since you can't just add methods to foreign structs, you only can add traits. In this case you can also use foreign struct in place of `YourMessage` since the trait already belongs to you.
