### ISSUE TITLE
Can I set_nodealy(true) for the tcpstream?

### ISSUE THREAD

**Issue by x1957** [snapview/tokio-tungstenite#250]
https://github.com/snapview/tokio-tungstenite/blob/05353b728ecff31a98feb6a75d404f648c5d5410/src/connect.rs#L49

I want to disable TCP Nagle Algorithm.

**Comment by daniel-abramov** [comment]
Sure. We've permanently disabled the TCP Nagle algorithm in `tungstenite`. We can only do it when using `connect` functions though (since the simple client functions get an abstract generic stream).

I'm not quite sure why we don't disable the Nagle algorithm explicitly anymore in `tokio-tungstenite`, we definitely [did it in the past](https://github.com/snapview/tokio-tungstenite/commit/e7c3ef525086eec00e41ec84a7678e7d92f527b9), but it seems like this change got removed during the migration to the newest versions of Tokio and support of different TLS backends.

**Comment by x1957** [comment]
Thanks daniel,
Do you consider add it back? Nagle cause 20ms latency for me.

**Comment by daniel-abramov** [comment]
Sure! If it's not disabled, then we indeed need to address it. I've opened a small PR for that.

**Comment by x1957** [comment]
thanks!
