### ISSUE TITLE
connect_async return type

### ISSUE THREAD

**Issue by wisespace-io** [snapview/tokio-tungstenite#26]
I would like to move the call below to a event_loop(), so I could properly match the connection errors,

https://github.com/wisespace-io/binance-rs/blob/master/src/websockets.rs#L66

however I didn't figure out what would be the return type in the call below

https://github.com/wisespace-io/binance-rs/blob/master/src/websockets.rs#L39

**Comment by agalakhov** [comment]
The return type of `connect_async` is `Box<Future>`.

However, you do further processing with `and_then` and `.map_err`, this makes the return type to be something like `MapErr<AndThen<Box<Future>>>` with lambda functions as extra parameters. That's why you can't specify the explicit return type here: you don't know the type of your lambda. The solution is usual: use `Box`. (Or use `impl trait` from the nightly Rust. if you use nightly).

```rust
pub fn connect_stream(&mut self, endpoint: String) -> Box<Future<Item = (), Error = errors::Error>> {
    let client = ...;
    Box::new(client)
}
```
