### ISSUE TITLE
Performance boost implementing `poll_write_vectored` and rustls 0.23

### ISSUE THREAD

**Issue by stormshield-gt** [snapview/tokio-tungstenite#322]
With new write-through API functionality of rustls 0.23 (https://github.com/rustls/rustls/pull/1640),  this library can implement `poll_write_vectored` on stream and gain a significant performance boost.

Basically, this is the same issue as in tokio-rustls https://github.com/rustls/tokio-rustls/issues/26, which has a current PR to solve it https://github.com/rustls/tokio-rustls/pull/45

**Comment by daniel-abramov** [comment]
This won't help [in our particular case](https://github.com/snapview/tungstenite-rs/issues/352#issuecomment-1537488614) as our underlying streams don't provide an implementation of vectored writes - this is caused by some known issues such as us relying solely on `tungstenite-rs` which was written under an assumption that streams implement `Read + Write`, instead of providing a sans-io implementation. But once we update the API surface of the `tungstenite-rs`, this would certainly be possible!

This is also **one of the reasons** why alternatives such as [`fastwebsockets`](https://github.com/denoland/fastwebsockets) are more performant.
