### ISSUE TITLE
Clarification regarding `CryptoProvider`

### ISSUE THREAD

**Issue by mhutter** [snapview/tokio-tungstenite#353]
From the discussions in #336 and #339 it is unclear what users are supposed to do now; nor is there any mention of this (breaking) change in the CHANGELOG; nor does the documentation say anything about it.

Unfortunately the note

> Disable default features for `rustls` giving the user more flexibility.

does not help for someone that never used rustls directly :)

**Comment by daniel-abramov** [comment]
We follow the semver to indicate breaking changes, but it's true that we did not specifically describe what must be called from the `rustls` crate for the problem to disappear. That was partially due to the fact that we discovered the particular error only after the release once some users started complaining.

> it is unclear what users are supposed to do now

Did you have a chance to check [suggestions from other users](https://github.com/snapview/tokio-tungstenite/issues/336#issuecomment-2424666934)? AFAIR the fix was mentioned a couple of times across different issues and solved the problem for those affected.

If I'm following you right, I assume you suggest including the information about that line of code (`rustls` stuff) in the README?

**Comment by mhutter** [comment]
Hi @daniel-abramov, thanks for taking the time!

> Did you have a chance to check suggestions from other users?

Yes, but there were multiple solutions mentioned, and most of them mention adding random additional dependencies and code, but none explained why.

From what I read I understand that I can add `rustls` as a direct dependency, and call either `rustls::crypto::aws_lc_rs::default_provider().install_default().unwrap()` or `rustls::crypto::ring::default_provider().install_default().unwrap()` to make the problem go away, but I don't understand _why_ this is happening.

Is this behavior that changed in the latest `rustls` version, did `tungstenite`'s usage of `rustls` change, or is the issue on my end?

**Comment by daniel-abramov** [comment]
You're right that it's a bit perplexing, especially for users unfamiliar with `rustls`. I agree that it's not optimal, and we might have resolved this by adding *another feature* that calls `install_default()`. However, we already have multiple TLS features, and I'm afraid that at some point, it gets too complicated. Hitting a balance between flexibility and simplicity is not always an easy task, but I'm open to solutions!

Meanwhile, I've added a small note to the README that links this discussion, so hopefully, it will make it less confusing!

**Comment by marvin-hansen** [comment]
Just a quick comment, I ran into this issue today and after some back and forth, the following solved the problem for me:

In Cargo.toml
```toml
rustls = { version = "0.23.17", features = ["ring"] }
tokio-tungstenite = { version = "0.24.0", features = ["rustls-tls-webpki-roots"]}
```

And then in main.rs

```rust 
#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // https://github.com/snapview/tokio-tungstenite/issues/353
    rustls::crypto::ring::default_provider().install_default().expect("Failed to install default rustls crypto provider");
  ...
}
```

I cross compile to multiple targets and this setup works reliably on all of them.
