### ISSUE TITLE
how to close the connection gracefully

### ISSUE THREAD

**Issue by bbigras** [snapview/tokio-tungstenite#4]
Does tokio-tungstenite has something to close the connection gracefully or does the users need to handle it (I guess with a Close frame and a timeout)?

**Comment by agalakhov** [comment]
Call close() and provide a closing code if you want. The connection will be closed gracefully. It will be closed as well if a close frame is received.

There is no way to send close handshake in the destructor since the state machine must exist to handle the close handshake. We can't do the handshake if the state machine is being dropped.

**Comment by application-developer-DA** [comment]
@bbigras although you can impement it the way you described, there is also an additional way to do this, recently tokio introduced a `close()` method to the `Sink` trait ([see "**Addition of `Sink::close`**"](https://tokio.rs/blog/tokio-io/)).

**Comment by application-developer-DA** [comment]
@bbigras currently the solution is to use `close()` function, it has been recently updated by introducing the following commit: https://github.com/snapview/tokio-tungstenite/commit/16c4693c91afc4c39514b0950c42b17eb4d674ba

Not very elegant (and does not allow to specify a code for now), but provides some sort of graceful close. We'll probably improve and extend this API in future releases.
