### ISSUE TITLE
0.6 release?

### ISSUE THREAD

**Issue by seanmonstar** [snapview/tokio-tungstenite#44]
Awesome library here! I've been working on a web framework that uses this for websockets, and while getting close to a viable release, it turns out I can't release with a git dependency :D Specifically, being able to use the new tokio crate, and construct a websocket stream after having done my own handshake. Does it seem like 0.6 would be possible soon?

**Comment by agalakhov** [comment]
Yes. It was actually planned for the previous week but this was not done due to other urgent tasks.
Do you have any special wishes for 0.6? Any functionality you're missing?

**Comment by ParadoxSpiral** [comment]
When do you plan to release the new version to crates.io?
I've switched to this crate from `websockets` because this is much nicer, but don't want to push the move until it's not a git dep anymore.

**Comment by application-developer-DA** [comment]
We thought about the release with the current state from master, but there is still one thing we're waiting for: `tokio-tls`. There is a patch in `Cargo.toml` of  `tokio-tungstenite`, without this patch the crate won't compile due to the `tokio-tls` dependency which currently uses the old version of `native-tls`. We hope that `tokio-tls` will get released soon with the new `native-tls` dependency (https://github.com/tokio-rs/tokio-tls/pull/43), at that point we can remove the [temporary] patch from our `Cargo.toml` and release a new version of `tokio-tungstenite`.

**Comment by zargony** [comment]
I'm too using tokio-tungstenite for websocket communication instead of the websocket crate because tokio-tungstenite's is nicer and easier to use.

Speaking of tokio_tls.. What do you think about making the `AutoStream` type public?
That'd be helpful for working with the resulting websocket item of `connect_async`. To handle the resulting websocket (e.g. keep it in a struct or pass it to a function), I need to give it's exact type. However, I can't use its type `WebSocketStream<AutoStream<S>>`, since AutoStream isn't public. So I always end up using the full type `WebSocketStream<StreamSwitcher<TcpStream, TlsStream<TcpStream>>>`, which also means that I need to add tokio_tls as a direct dependency to get the `StreamSwitcher` type, which is a little unconvenient.

**Comment by agalakhov** [comment]
I even feel that `AutoStream` should be a separate crate. There are many cases when the same code could either use TLS or not, and this has nothing to do with WebSocket. We had to reinvent many wheels for Tungstenite.

**Comment by zargony** [comment]
In a separate crate or maybe in tokio_tls. However, the name `AutoStream` could be a little confusing since it sounds like the stream would automatically detect TLS. Maybe something like `OptionalTlsStream` would be better if used outside of tokio_tungstenite.

**Comment by agalakhov** [comment]
Totally agree.

**Comment by application-developer-DA** [comment]
Or maybe even something more general like `StreamType` / `NetworkStream` or something like that.

**Comment by application-developer-DA** [comment]
**UPD.** We're not waiting for https://github.com/tokio-rs/tokio-tls/pull/43 anymore. According to the latest information, Carl has suggested to merge the following pull request: https://github.com/tokio-rs/tokio-tls/pull/45.

Once the changes are merged and published, we can use the version of `tokio-tls` from crates.io.

**Comment by zeyla** [comment]
The PR was merged and tokio-tls 0.2 has been published.

**Comment by application-developer-DA** [comment]
Yes, I think we're ready for release now.

ping @agalakhov 

@zargony the `AutoStream` changes and other small things might be delivered in the upcoming patch version improvements, unless you want to send a pull request before @agalakhov publishes a release ;)

**Comment by agalakhov** [comment]
Version 0.6.0 released.
