### ISSUE TITLE
Not receiving incoming messages via stream

### ISSUE THREAD

**Issue by EverlastingBugstopper** [snapview/tokio-tungstenite#77]
I have some `tokio-tungstenite` code that's using the latest commit on master and it works _beautifully_ on my Macbook and my CI for Windows passes just fine. The problem is that it seems like the reader never receives any messages!

My code for repro can be found [here](https://github.com/cloudflare/wrangler/pull/991/files) and it's loosely based on the pattern described in `examples/client.rs`.

I understand that I'm using the latest commit on master and I'm not expecting this to be stable but wanted to get it on the radar :) Please let me know if there's anything else I can do to help with this!

**Comment by EverlastingBugstopper** [comment]
actually jk i did not do due diligence it seems like this code does not work on my mac either. classic "it worked yesterday" and "it works on my machine". I'm closing this 😄 keep up the good work

**Comment by EverlastingBugstopper** [comment]
Reopening this as I cannot figure out why I'm not receiving any messages for the life of me - any help is greatly appreciated.

**Comment by agalakhov** [comment]
Looks like you try to `await` send and receive on the same socket. This won't work. You can't receive anything while awaiting send.

**Comment by sdroege** [comment]
Awaiting the read and write side of the socket in parallel should work fine, that's one of the underlying assumptions of `split()` on a `Sink+Stream`. When space is available for writing, writing will wake, when space for reading is available then reading will wake and otherwise both are (asynchronously, non-blocking!) waiting for either of the two conditions.

But from what I can see the problem here is `keep_alive()`. That will busy wait with that loop until the `KEEP_ALIVE_INTERVAL` is reached and won't allow anything else in the same task to run in the meantime. You probably want to use `tokio::time::interval()` here instead for doing the same thing asynchronously.

**Comment by EverlastingBugstopper** [comment]
@sdroege that was it!!!! Thank you so much for your help on this :)
